"""
This type stub file was generated by pyright.
"""

import click

def scan_known_people(known_people_folder): # -> tuple[list[Any], list[Any]]:
    ...

def print_result(filename, name, distance, show_distance=...): # -> None:
    ...

def test_image(image_to_check, known_names, known_face_encodings, tolerance=..., show_distance=...): # -> None:
    ...

def image_files_in_folder(folder): # -> list[Any]:
    ...

def process_images_in_process_pool(images_to_check, known_names, known_face_encodings, number_of_cpus, tolerance, show_distance): # -> None:
    ...

@click.command()
@click.argument('known_people_folder')
@click.argument('image_to_check')
@click.option('--cpus', default=1, help='number of CPU cores to use in parallel (can speed up processing lots of images). -1 means "use all in system"')
@click.option('--tolerance', default=0.6, help='Tolerance for face comparisons. Default is 0.6. Lower this if you get multiple matches for the same person.')
@click.option('--show-distance', default=False, type=bool, help='Output face distance. Useful for tweaking tolerance setting.')
def main(known_people_folder, image_to_check, cpus, tolerance, show_distance): # -> None:
    ...

if __name__ == "__main__":
    ...
