"""
This type stub file was generated by pyright.
"""

import click

def print_result(filename, location): # -> None:
    ...

def test_image(image_to_check, model): # -> None:
    ...

def image_files_in_folder(folder): # -> list[Any]:
    ...

def process_images_in_process_pool(images_to_check, number_of_cpus, model): # -> None:
    ...

@click.command()
@click.argument('image_to_check')
@click.option('--cpus', default=1, help='number of CPU cores to use in parallel. -1 means "use all in system"')
@click.option('--model', default="hog", help='Which face detection model to use. Options are "hog" or "cnn".')
def main(image_to_check, cpus, model): # -> None:
    ...

if __name__ == "__main__":
    ...
